"""
generate_readme.py
Generates README.md for jogi-rajeshkumar.

Stat SVGs are generated by lowlighter/metrics inside GitHub Actions
and committed to assets/stats/ — no external API calls needed.
"""

import urllib.request
import json
from datetime import datetime, timezone

GITHUB_USERNAME = "jogi-rajeshkumar"

# ── Skill Badges ──────────────────────────────────────────────────────────────

def badges():
    badge_list = [
        ("Python",           "3776AB", "python",            "white"),
        ("JavaScript",       "F7DF1E", "javascript",        "black"),
        ("SQL",              "4479A1", "mysql",             "white"),
        ("HTML5",            "E34F26", "html5",             "white"),
        ("CSS3",             "1572B6", "css3",              "white"),
        ("PyTorch",          "EE4C2C", "pytorch",           "white"),
        ("TensorFlow",       "FF6F00", "tensorflow",        "white"),
        ("Keras",            "D00000", "keras",             "white"),
        ("OpenCV",           "5C3EE8", "opencv",            "white"),
        ("HuggingFace",      "FFD21E", "huggingface",       "black"),
        ("scikit--learn",    "F7931E", "scikitlearn",       "white"),
        ("AWS",              "232F3E", "amazonwebservices", "white"),
        ("Docker",           "2496ED", "docker",            "white"),
        ("GitHub%20Actions", "2088FF", "githubactions",     "white"),
        ("Linux",            "FCC624", "linux",             "black"),
        ("Django",           "092E20", "django",            "white"),
        ("Flask",            "000000", "flask",             "white"),
        ("FastAPI",          "009688", "fastapi",           "white"),
        ("Apache%20Spark",   "E25A1C", "apachespark",       "white"),
        ("PostgreSQL",       "4169E1", "postgresql",        "white"),
        ("MongoDB",          "47A248", "mongodb",           "white"),
    ]
    lines = []
    for label, color, logo, font_color in badge_list:
        lines.append(
            f'<img src="https://img.shields.io/badge/{label}-{color}'
            f'?style=for-the-badge&logo={logo}&logoColor={font_color}" alt="{label}"/>'
        )
    rows = []
    for i in range(0, len(lines), 5):
        rows.append("\n".join(lines[i:i+5]))
    return "\n\n".join(rows)

# ── Fetch top repos ───────────────────────────────────────────────────────────

def fetch_top_repos():
    try:
        url = f"https://api.github.com/users/{GITHUB_USERNAME}/repos?per_page=100&sort=updated"
        req = urllib.request.Request(url, headers={"User-Agent": "readme-generator"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            repos = json.loads(resp.read().decode())
        repos = [r for r in repos if not r.get("fork") and r["name"] != GITHUB_USERNAME]
        repos.sort(key=lambda r: r.get("stargazers_count", 0), reverse=True)
        return repos[:6]
    except Exception:
        return []

def repo_cards(repos):
    if not repos:
        return '<tr><td align="center"><em>Repositories loading...</em></td></tr>'
    cells = []
    for repo in repos:
        name = repo["name"]
        cell = (
            f'<td align="center" width="33%">\n'
            f'<a href="https://github.com/{GITHUB_USERNAME}/{name}">\n'
            f'<img src="https://gh-card.dev/repos/{GITHUB_USERNAME}/{name}.svg?fullname=" '
            f'width="100%" alt="{name}"/>\n'
            f'</a>\n'
            f'</td>'
        )
        cells.append(cell)
    rows = []
    for i in range(0, len(cells), 3):
        chunk = cells[i:i+3]
        while len(chunk) < 3:
            chunk.append('<td width="33%"></td>')
        rows.append("<tr>\n" + "\n".join(chunk) + "\n</tr>")
    return "\n".join(rows)

# ── README builder ────────────────────────────────────────────────────────────

def generate():
    now   = datetime.now(timezone.utc).strftime("%d %B %Y, %H:%M UTC")
    repos = fetch_top_repos()

    readme = f"""<div align="center">
<img src="https://capsule-render.vercel.app/api?type=waving&color=gradient&customColorList=6,11,20&height=200&section=header&text=Rajesh%20Kumar%20Jogi&fontSize=50&fontColor=fff&animation=twinkling&fontAlignY=35&desc=Computer%20Vision%20Engineer%20%7C%20AI%20Researcher%20%7C%20MSc%20AI%20Student&descAlignY=55&descSize=18" width="100%"/>

<img src="https://komarev.com/ghpvc/?username={GITHUB_USERNAME}&color=0891b2&style=for-the-badge&label=PROFILE+VIEWS" alt="Profile Views"/>

<a href="https://jogi-rajeshkumar.vercel.app"><img src="https://img.shields.io/badge/Portfolio-jogi--rajeshkumar.vercel.app-0891b2?style=for-the-badge&logo=vercel&logoColor=white" alt="Portfolio"/></a>
<a href="https://linkedin.com/in/jogi-rajesh-kumar"><img src="https://img.shields.io/badge/LinkedIn-jogi--rajesh--kumar-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn"/></a>
<a href="mailto:rajeshkumarjogi.2098@gmail.com"><img src="https://img.shields.io/badge/Email-rajeshkumarjogi.2098%40gmail.com-EA4335?style=for-the-badge&logo=gmail&logoColor=white" alt="Email"/></a>
<a href="https://github.com/{GITHUB_USERNAME}"><img src="https://img.shields.io/badge/GitHub-jogi--rajeshkumar-181717?style=for-the-badge&logo=github&logoColor=white" alt="GitHub"/></a>
</div>

---

## 🧠 Professional Profile

> MSc Artificial Intelligence student with **3+ years** of professional experience specialising in **Computer Vision**, **Machine Learning**, and **Real-Time Analytics**. Proven track record in leading teams to deploy production-level ML modules that optimise system latency and throughput. Currently researching **privacy-preserving Federated Learning** for EEG-based emotion recognition on edge devices. Expert in building cross-platform AI applications and robust security solutions for **healthcare, finance, and government** sectors.

---

## 💼 Professional Experience

### 🟢 AI Agent Developer — Green Environment Ltd, London *(Oct 2025 – Present)*
- 🤖 Designing intelligent AI-driven systems to enhance automation for **ECO4** and **GBIS** initiatives
- 🌱 Applying Computer Vision & ML to real-world **sustainability challenges** within the Green Deal sector
- 🔗 Collaborating with data engineering and energy assessment teams through R&D

### 🔵 Computer Vision Software Engineer (Team Lead) — Boolean Brain Technologies *(Dec 2023 – Aug 2024)*
- ⚡ Led a team integrating Python ML modules into production, reducing **API latency by 25%**
- 🔧 Refactored legacy inference model code, boosting **system throughput by 1.6×**
- 🌐 Developed customised Django web applications, decreasing **support tickets by 30%**

### 🟠 Computer Vision Engineer — Timing Technologies India Pvt. Ltd *(May 2023 – Nov 2023)*
- 🏛️ Built **facial recognition** and Bib Detection apps for Government Selections across Indian states
- 🔒 Deployed a secure examination browser on **100+ client devices** using PyInstaller
- 🎯 Fine-tuned **YOLOv5** and **ResNet-50** for edge deployment, achieving **>90% precision**

### 🟡 AI/ML Intern — ThoughtGreen Technologies *(Jan 2023 – Apr 2023)*
- 📚 Researched Bib detection algorithms; trained models with **PyTorch** and **TensorFlow**
- 🔬 Executed comprehensive model testing, evaluation, and hyperparameter optimisation

### 🔴 Freelance ML Developer — Independent *(2020 – 2022)*
- 👤 Designed biometric facial attendance and fraud detection systems
- 🛠️ Delivered bespoke tools for clients in **finance, transportation, and administration**

---

## 🎓 Education

**🏫 MSc Artificial Intelligence (with Industrial Placement)**
University of East London, London, UK | *Sept 2024 – May 2026*

| Module | Focus |
|--------|-------|
| Intelligent Systems | AI Planning & Reasoning |
| Big Data Analytics | Distributed Processing at Scale |
| Machine Learning on Big Data | Large-scale ML Pipelines |

> 📌 **Dissertation:** *Federated Learning for EEG-Based Emotion Recognition Across Edge Devices*

---

## 🚀 Key Projects

| Project | Description | Stack |
|---------|-------------|-------|
| 🧠 **eeg-fl-emotion** | Privacy-preserving emotion recognition via Federated Learning | PyTorch, FedAvg, Edge Devices |
| 🛰️ **Satellite Object Recognition** | Memory-efficient deep learning for fine-grained classification | Keras, CNNs, FAIR1M Dataset |
| 🎭 **Real-Time Face Analysis** | Live browser-based age, emotion & gender detection | Flask, PyTorch, face-api.js |
| 👁️ **Real-Time CV Monitoring** | Eye state detection & gesture-based volume control | MediaPipe, OpenCV, Dlib |
| 📈 **Financial Portfolio Optimizer** | Stock market optimisation & automated data pipelines | Pandas, NumPy |
| 🖥️ **DevOps Server Monitor** | Server uptime monitor with Telegram alerts | Python, Telegram API |

---

## 🛠️ Technical Arsenal

<div align="center">

{badges()}

</div>

---

## 📊 GitHub Analytics

<div align="center">
<table>
<tr>
<td align="center" width="50%">
<a href="https://github.com/{GITHUB_USERNAME}">
<img src="assets/stats/github-stats.svg" alt="GitHub Stats" width="100%"/>
</a>
</td>
<td align="center" width="50%">
<a href="https://github.com/{GITHUB_USERNAME}">
<img src="https://streak-stats.demolab.com/?user={GITHUB_USERNAME}&theme=tokyonight&hide_border=true" alt="GitHub Streak" width="100%"/>
</a>
</td>
</tr>
<tr>
<td align="center" width="50%">
<a href="https://github.com/{GITHUB_USERNAME}">
<img src="assets/stats/top-langs.svg" alt="Top Languages" width="100%"/>
</a>
</td>
<td align="center" width="50%">
<a href="https://github.com/{GITHUB_USERNAME}">
<img src="https://github-readme-activity-graph.vercel.app/graph?username={GITHUB_USERNAME}&theme=tokyo-night&hide_border=true&area=true" alt="Activity Graph" width="100%"/>
</a>
</td>
</tr>
</table>
</div>

<div align="center">
<a href="https://github.com/{GITHUB_USERNAME}">
<img src="assets/stats/achievements.svg" alt="GitHub Achievements" width="100%"/>
</a>
</div>

---

## 📌 Featured Repositories

<div align="center">
<table>
{repo_cards(repos)}
</table>
</div>

---

## 🏆 Certifications

| 🎖️ Certificate | 🏢 Issuer |
|----------------|----------|
| 🤖 Career Essentials in Generative AI | Microsoft & LinkedIn |
| 👁️ OpenAI API: Vision | LinkedIn Learning |
| 🐳 Docker Foundations Professional Certificate | Docker, Inc. |
| 🧮 ML Algorithms | Great Learning |
| 🍓 Raspberry Pi Emergency Alert Helmet — Edge AI | EC-Council |
| 🔐 SQL Injection Attacks — Cybersecurity | EC-Council |
| 🌐 HTML for Programmers | LinkedIn Learning |
| 📡 Networking Fundamentals | Udemy |
| 💼 AI and Business Strategy | LinkedIn |

---

## 📬 Let's Connect

<div align="center">
<a href="https://jogi-rajeshkumar.vercel.app"><img src="https://img.shields.io/badge/Portfolio-Visit_Now-0891b2?style=for-the-badge&logo=vercel&logoColor=white" alt="Portfolio"/></a>
<a href="https://linkedin.com/in/jogi-rajesh-kumar"><img src="https://img.shields.io/badge/LinkedIn-Connect-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn"/></a>
<a href="https://github.com/{GITHUB_USERNAME}"><img src="https://img.shields.io/badge/GitHub-Follow-181717?style=for-the-badge&logo=github&logoColor=white" alt="GitHub"/></a>
<a href="mailto:rajeshkumarjogi.2098@gmail.com"><img src="https://img.shields.io/badge/Email-Say%20Hello-EA4335?style=for-the-badge&logo=gmail&logoColor=white" alt="Email"/></a>
</div>

---

<div align="center">
<img src="https://capsule-render.vercel.app/api?type=waving&color=gradient&customColorList=6,11,20&height=100&section=footer" width="100%"/>

*🔄 README auto-updated on **{now}** via GitHub Actions*
</div>
"""

    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme)
    print(f"✅ README.md generated at {now}")


if __name__ == "__main__":
    generate()
